/**
 * SSA/ASS conformance based on the SSA v4.00+ spec (Advanced SubStation Alpha) and real-world
 * files produced by Aegisub and ffmpeg.
 */
import { parseText, renderVTTCueString } from 'media-captions';

const STYLE_FORMAT =
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding';
const EVENT_FORMAT =
  'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text';

function ass(
  styles: string[],
  events: string[],
  info: string[] = ['PlayResX: 1280', 'PlayResY: 720'],
) {
  return [
    '[Script Info]',
    'ScriptType: v4.00+',
    ...info,
    '',
    '[V4+ Styles]',
    STYLE_FORMAT,
    ...styles,
    '',
    '[Events]',
    EVENT_FORMAT,
    ...events,
    '',
  ].join('\n');
}

const DEFAULT =
  'Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1';
const dialogue = (text: string, style = 'Default', layer = 0) =>
  `Dialogue: ${layer},0:00:01.00,0:00:05.00,${style},,0,0,0,,${text}`;

async function parse(text: string) {
  return parseText(text, { type: 'ass', errors: true });
}

describe('script info', () => {
  test('PlayRes scales font size, margins, and outline', async () => {
    const { cues } = await parse(ass([DEFAULT], [dialogue('x')]));
    expect(cues[0].textStyle?.fontSize).toEqual({ unit: 'vh', value: 6.6667 });
    expect(cues[0].layout?.bottom).toBe(1.389);
    expect(cues[0].layout?.maxWidth).toBe(98.438);
    expect(cues[0].textStyle?.stroke).toEqual({
      width: { unit: 'vh', value: 0.5556 },
      color: 'rgba(0,0,0,1)',
    });
  });

  test('defaults to 384x288 when PlayRes is missing', async () => {
    const { cues } = await parse(ass([DEFAULT], [dialogue('x')], []));
    expect(cues[0].textStyle?.fontSize).toEqual({ unit: 'vh', value: 16.6667 });
  });

  test('WrapStyle 2 turns soft breaks into hard breaks', async () => {
    const { cues } = await parse(ass([DEFAULT], [dialogue('a\\nb\\Nc')], ['WrapStyle: 2']));
    expect(cues[0].text).toBe('a\nb\nc');
    const soft = await parse(ass([DEFAULT], [dialogue('a\\nb\\Nc')]));
    expect(soft.cues[0].text).toBe('a b\nc');
  });

  test('comment lines are ignored', async () => {
    const { cues, metadata } = await parse(
      ass([DEFAULT], [dialogue('x')], ['; generated by test', 'Title: Demo']),
    );
    expect(metadata.Title).toBe('Demo');
    expect(cues).toHaveLength(1);
  });
});

describe('colours', () => {
  test('&HAABBGGRR, &HBBGGRR&, and decimal forms', async () => {
    const styles = [
      'Style: A,Arial,48,&H80FF8000,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,0,0,0,1',
      'Style: B,Arial,48,&H0000FF&,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,0,0,0,1',
      'Style: C,Arial,48,16777215,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,0,0,0,1',
    ];
    const { cues } = await parse(
      ass(styles, [dialogue('a', 'A'), dialogue('b', 'B'), dialogue('c', 'C')]),
    );
    expect(cues[0].textStyle?.color).toBe('rgba(0,128,255,0.498)');
    expect(cues[1].textStyle?.color).toBe('rgba(255,0,0,1)');
    expect(cues[2].textStyle?.color).toBe('rgba(255,255,255,1)');
  });

  test('inline colour tags produce hex colour classes', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('{\\c&H00FF00&}green{\\1c&HFF0000&}blue{\\r}plain')]),
    );
    expect(cues[0].text).toBe('<c.#00ff00>green</c><c.#0000ff>blue</c>plain');
    expect(renderVTTCueString(cues[0])).toBe(
      '<span style="color: #00ff00;">green</span><span style="color: #0000ff;">blue</span>plain',
    );
  });
});

describe('alignment', () => {
  const cases: Array<[number, string, string]> = [
    [1, 'left', 'bottom'],
    [2, 'center', 'bottom'],
    [3, 'right', 'bottom'],
    [4, 'left', 'top'],
    [5, 'center', 'top'],
    [6, 'right', 'top'],
    [7, 'left', 'top'],
    [8, 'center', 'top'],
    [9, 'right', 'top'],
  ];

  test.each(cases)('numpad alignment %i -> %s', async (an, align, side) => {
    const { cues } = await parse(ass([DEFAULT], [dialogue(`{\\an${an}}x`)]));
    expect(cues[0].textStyle?.textAlign).toBe(align);
    expect(cues[0].layout?.[side as 'top' | 'bottom']).toBeDefined();
    if (an >= 4 && an <= 6) expect(cues[0].layout?.top).toBe(50);
  });

  test('legacy \\a values use the SSA v4.00 scheme', async () => {
    const { cues } = await parse(
      ass(
        [DEFAULT],
        [
          dialogue('{\\a6}top centre'),
          dialogue('{\\a10}middle centre'),
          dialogue('{\\a1}bottom left'),
        ],
      ),
    );
    expect(cues[0].layout?.top).toBe(1.389);
    expect(cues[1].layout?.top).toBe(50);
    expect(cues[2].textStyle?.textAlign).toBe('left');
    expect(cues[2].layout?.bottom).toBeDefined();
  });

  test('[V4 Styles] alignment column uses the legacy scheme too', async () => {
    const text = [
      '[V4 Styles]',
      STYLE_FORMAT.replace('OutlineColour', 'TertiaryColour'),
      'Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,6,10,10,10,1',
      '',
      '[Events]',
      EVENT_FORMAT,
      dialogue('top centre'),
      '',
    ].join('\n');
    const { cues } = await parse(text);
    expect(cues[0].layout?.top).toBeDefined();
    expect(cues[0].textStyle?.textAlign).toBe('center');
  });
});

describe('events', () => {
  test('Layer maps to z-order and is exposed on the cue', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('back', 'Default', 0), dialogue('front', 'Default', 3)]),
    );
    expect(cues[0].layer).toBeUndefined();
    expect(cues[1].layer).toBe(3);
    expect(cues[1].layer).toBe(3);
  });

  test('Name becomes a voice span with angle brackets stripped', async () => {
    const { cues } = await parse(
      ass([DEFAULT], ['Dialogue: 0,0:00:01.00,0:00:05.00,Default,Rin <lead>,0,0,0,,hi']),
    );
    expect(cues[0].text).toBe('<v Rin lead>hi');
  });

  test('unknown style names fall back to the WebVTT defaults and *-prefixed names are resolved', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('x', 'Missing'), dialogue('y', '*Default')]),
    );
    expect(cues[0].layout).toBeUndefined();
    expect(cues[0].textStyle).toBeUndefined();
    expect(cues[1].textStyle?.color).toBe('rgba(255,255,255,1)');
  });

  test('per-dialogue margins override the style margins', async () => {
    const { cues } = await parse(
      ass([DEFAULT], ['Dialogue: 0,0:00:01.00,0:00:05.00,Default,,128,0,72,,x']),
    );
    // MarginR of 0 means "use the style margin" per the ASS spec.
    expect(cues[0].layout?.left).toBe(54.609);
    expect(cues[0].layout?.maxWidth).toBe(89.219);
    expect(cues[0].layout?.bottom).toBe(10);
  });

  test('Comment events are skipped and field order follows the Format line', async () => {
    const text = [
      '[Events]',
      'Format: Start, End, Layer, Text, Style',
      'Comment: 0:00:00.00,0:00:01.00,0,ignored,Default',
      'Dialogue: 0:00:01.00,0:00:02.00,1,Hello, world,Default',
      '',
    ].join('\n');
    const { cues } = await parse(text);
    expect(cues).toHaveLength(1);
    // Text is not the last field here, so the comma split is honoured as declared.
    expect(cues[0].text).toBe('Hello');
  });

  test('timestamps use centiseconds and hours may be one digit', async () => {
    const { cues } = await parse(
      ass([DEFAULT], ['Dialogue: 0,1:02:03.45,1:02:04.50,Default,,0,0,0,,x']),
    );
    expect(cues[0].startTime).toBe(3723.45);
    expect(cues[0].endTime).toBe(3724.5);
  });
});

describe('override tags', () => {
  test('formatting toggles and reset', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('{\\i1}i{\\b1}ib{\\i0}b{\\u1}bu{\\r}plain{\\b}toggle{\\b}off')]),
    );
    expect(cues[0].text).toBe('<i>i<b>ib</b></i><b>b<u>bu</u></b>plain<b>toggle</b>off');
  });

  test('karaoke durations become timestamp tags', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('{\\k50}Ka{\\K100}ra{\\kf50}o{\\ko50}ke')]),
    );
    // `\\K`/`\\kf`/`\\ko` syllables are additionally wrapped in spans that carry the sweep
    // animation (see ssa-typesetting.test.ts); plain `\\k` only needs the timestamp.
    expect(cues[0].text).toBe(
      '<00:00:01.000>Ka<00:00:01.500><c.s-0>ra</c><00:00:02.500><c.s-1>o</c><00:00:03.000><c.s-2>ke</c>',
    );
    expect(Object.keys(cues[0].spans!)).toEqual(['0', '1', '2']);
  });

  test('drawing commands become a drawing span and hard spaces are preserved', async () => {
    const { cues } = await parse(
      ass([DEFAULT], [dialogue('{\\p1}m 0 0 l 10 10{\\p0}text\\hmore')]),
    );
    // Drawings used to be dropped; they are now rendered as an inline SVG span with no text.
    expect(cues[0].text).toBe('<c.s-0></c>text&nbsp;more');
    expect(cues[0].spans!['0'].drawing?.path).toBe('M0 0L10 10Z');
  });

  test('unsupported tags are stripped without losing text', async () => {
    const { cues } = await parse(
      ass(
        [DEFAULT],
        [
          dialogue(
            '{\\fax0.2\\fay0\\org(10,10)\\pbo-2\\fe1\\iclip(0,0,10,10)}visible {\\kt10}text',
          ),
        ],
      ),
    );
    expect(cues[0].text).toBe('visible text');
    expect(cues[0].spans).toBeUndefined();
    expect(cues[0].animations).toBeUndefined();
  });

  test('typesetting tags keep the text intact while adding spans and animations', async () => {
    const { cues } = await parse(
      ass(
        [DEFAULT],
        [dialogue('{\\fad(200,200)\\t(\\fs40)\\fnArial\\blur2}visible {\\move(0,0,10,10)}text')],
      ),
    );
    // `\\fnArial` matches the style font so only the blur differs. `\\t` precedes the blur and
    // no text has been emitted, so it animates the cue box as a whole.
    expect(cues[0].text).toBe('<c.s-0>visible text</c>');
    expect(cues[0].spans!['0']).toEqual({ blur: { unit: 'vh', value: 0.2778 } });
    expect(cues[0].animations!.map((a) => a.target)).toEqual(['display', 'cue', 'display']);
    expect(cues[0].layout?.fixed).toBe(true);
  });

  test('\\pos produces a fixed, translated cue', async () => {
    const { cues } = await parse(ass([DEFAULT], [dialogue('{\\pos(640,360)}x')]));
    expect(cues[0].layout).toEqual({
      width: 'max-content',
      left: 50,
      top: 50,
      translate: { x: -0.5, y: -1 },
      fixed: true,
    });
  });

  test('angle brackets and ampersands in text are escaped', async () => {
    const { cues } = await parse(ass([DEFAULT], [dialogue('<b>not a tag</b> & co')]));
    expect(cues[0].text).toBe('&lt;b>not a tag&lt;/b> &amp; co');
    expect(renderVTTCueString(cues[0])).toBe('&lt;b&gt;not a tag&lt;/b&gt; &amp; co');
  });
});

describe('embedded fonts', () => {
  test('[Fonts] sections are decoded', async () => {
    const text =
      ass([DEFAULT], [dialogue('x')]) +
      ['[Fonts]', 'fontname: test_B.ttf', '!!!!"!!!', '', ''].join('\n');
    const { fonts } = await parse(text);
    expect(fonts).toHaveLength(1);
    expect(fonts![0].name).toBe('test_B.ttf');
    // `"` is value 1, which lands in the top bits of the first byte of its group.
    expect(Array.from(fonts![0].data)).toEqual([0, 0, 0, 4, 0, 0]);
  });
});
